CREATE TABLE simulasi_interaksi_obat (
    id INT AUTO_INCREMENT PRIMARY KEY,
    obat1 VARCHAR(100) NOT NULL,
    obat2 VARCHAR(100) NOT NULL,
    simulasi TEXT NOT NULL
);

INSERT INTO simulasi_interaksi_obat (obat1, obat2, simulasi) VALUES
('Amoxicillin', 'Paracetamol', 'Aman dikonsumsi bersamaan'),
('Amoxicillin', 'Ibuprofen', 'Aman dikonsumsi bersamaan'),
('Amoxicillin', 'Cetirizine', 'Aman dikonsumsi bersamaan'),
('Amoxicillin', 'Antasida', 'Tidak aman: antasida dapat mengurangi penyerapan antibiotik'),
('Amoxicillin', 'Warfarin', 'Tidak aman: meningkatkan risiko perdarahan'),
('Paracetamol', 'Ibuprofen', 'Aman dikonsumsi bersamaan'),
('Paracetamol', 'Alkohol', 'Tidak aman: meningkatkan risiko kerusakan hati'),
('Paracetamol', 'Rifampicin', 'Tidak aman: meningkatkan toksisitas hati'),
('Ibuprofen', 'Aspirin', 'Tidak aman: meningkatkan risiko perdarahan lambung'),
('Ibuprofen', 'Prednisone', 'Tidak aman: meningkatkan risiko tukak lambung'),
('Ibuprofen', 'Omeprazole', 'Aman dikonsumsi bersamaan'),
('Aspirin', 'Warfarin', 'Tidak aman: risiko perdarahan sangat tinggi'),
('Aspirin', 'Clopidogrel', 'Tidak aman: meningkatkan risiko perdarahan'),
('Aspirin', 'Vitamin C', 'Aman dikonsumsi bersamaan'),
('Cetirizine', 'Loratadine', 'Tidak aman: meningkatkan rasa kantuk'),
('Cetirizine', 'Paracetamol', 'Aman dikonsumsi bersamaan'),
('Cetirizine', 'Diazepam', 'Tidak aman: menyebabkan sedasi berlebihan'),
('Diazepam', 'Alkohol', 'Tidak aman: dapat menekan pernapasan'),
('Diazepam', 'Paracetamol', 'Aman dikonsumsi bersamaan'),
('Diazepam', 'Alprazolam', 'Tidak aman: risiko overdosis sedatif'),
('Metformin', 'Insulin', 'Aman dikonsumsi bersamaan dengan pengawasan'),
('Metformin', 'Alkohol', 'Tidak aman: meningkatkan risiko asidosis laktat'),
('Metformin', 'Ciprofloxacin', 'Tidak aman: mempengaruhi kadar gula darah'),
('Insulin', 'Glibenclamide', 'Tidak aman: menyebabkan hipoglikemia berat'),
('Insulin', 'Paracetamol', 'Aman dikonsumsi bersamaan'),
('Glibenclamide', 'Alkohol', 'Tidak aman: meningkatkan hipoglikemia'),
('Omeprazole', 'Antasida', 'Aman dikonsumsi bersamaan'),
('Omeprazole', 'Clopidogrel', 'Tidak aman: mengurangi efektivitas clopidogrel'),
('Omeprazole', 'Paracetamol', 'Aman dikonsumsi bersamaan'),
('Ciprofloxacin', 'Susu', 'Tidak aman: mengurangi penyerapan antibiotik'),
('Ciprofloxacin', 'Antasida', 'Tidak aman: efektivitas antibiotik menurun'),
('Ciprofloxacin', 'Paracetamol', 'Aman dikonsumsi bersamaan'),
('Ciprofloxacin', 'Warfarin', 'Tidak aman: meningkatkan risiko perdarahan'),
('Rifampicin', 'Paracetamol', 'Tidak aman: meningkatkan kerusakan hati'),
('Rifampicin', 'Vitamin B Complex', 'Aman dikonsumsi bersamaan'),
('Rifampicin', 'Pil KB', 'Tidak aman: menurunkan efektivitas kontrasepsi'),
('Prednisone', 'Ibuprofen', 'Tidak aman: risiko perdarahan lambung'),
('Prednisone', 'Paracetamol', 'Aman dikonsumsi bersamaan'),
('Prednisone', 'Vaksin hidup', 'Tidak aman: menurunkan respons imun'),
('Salbutamol', 'Paracetamol', 'Aman dikonsumsi bersamaan'),
('Salbutamol', 'Kafein', 'Tidak aman: meningkatkan detak jantung'),
('Salbutamol', 'Propranolol', 'Tidak aman: mengurangi efek salbutamol'),
('Propranolol', 'Amlodipine', 'Aman dengan pengawasan dokter'),
('Propranolol', 'Salbutamol', 'Tidak aman: memicu sesak napas'),
('Amlodipine', 'Simvastatin', 'Aman dikonsumsi bersamaan'),
('Amlodipine', 'Sildenafil', 'Tidak aman: tekanan darah turun drastis'),
('Simvastatin', 'Alkohol', 'Tidak aman: meningkatkan kerusakan hati'),
('Simvastatin', 'Erythromycin', 'Tidak aman: meningkatkan risiko kerusakan otot'),
('Simvastatin', 'Paracetamol', 'Aman dikonsumsi bersamaan'),
('Erythromycin', 'Simvastatin', 'Tidak aman: risiko rhabdomyolysis'),
('Erythromycin', 'Paracetamol', 'Aman dikonsumsi bersamaan'),
('Erythromycin', 'Warfarin', 'Tidak aman: meningkatkan perdarahan'),
('Warfarin', 'Vitamin K', 'Tidak aman: menurunkan efektivitas warfarin'),
('Warfarin', 'Paracetamol', 'Aman dengan pemantauan'),
('Warfarin', 'NSAID', 'Tidak aman: meningkatkan risiko perdarahan'),
('Clopidogrel', 'Aspirin', 'Tidak aman: risiko perdarahan meningkat'),
('Clopidogrel', 'Omeprazole', 'Tidak aman: mengurangi efektivitas clopidogrel'),
('Clopidogrel', 'Paracetamol', 'Aman dikonsumsi bersamaan'),
('Loratadine', 'Paracetamol', 'Aman dikonsumsi bersamaan'),
('Loratadine', 'Diazepam', 'Tidak aman: meningkatkan rasa kantuk'),
('Alprazolam', 'Alkohol', 'Tidak aman: depresi sistem saraf pusat'),
('Alprazolam', 'Diazepam', 'Tidak aman: sedasi berat'),
('Alprazolam', 'Paracetamol', 'Aman dikonsumsi bersamaan'),
('Antasida', 'Tetracycline', 'Tidak aman: menurunkan penyerapan antibiotik'),
('Antasida', 'Paracetamol', 'Aman dikonsumsi bersamaan'),
('Tetracycline', 'Susu', 'Tidak aman: penyerapan antibiotik menurun'),
('Tetracycline', 'Vitamin C', 'Aman dikonsumsi bersamaan'),
('Tetracycline', 'Antasida', 'Tidak aman: efektivitas antibiotik berkurang'),
('Vitamin C', 'Zinc', 'Aman dikonsumsi bersamaan'),
('Vitamin C', 'Paracetamol', 'Aman dikonsumsi bersamaan'),
('Zinc', 'Doxycycline', 'Tidak aman: mengurangi penyerapan antibiotik'),
('Doxycycline', 'Susu', 'Tidak aman: efektivitas antibiotik turun'),
('Doxycycline', 'Paracetamol', 'Aman dikonsumsi bersamaan'),
('Doxycycline', 'Antasida', 'Tidak aman: mengurangi penyerapan'),
('Sildenafil', 'Nitrat', 'Tidak aman: tekanan darah turun drastis'),
('Sildenafil', 'Amlodipine', 'Tidak aman: hipotensi berat'),
('Sildenafil', 'Paracetamol', 'Aman dikonsumsi bersamaan'),
('Nitrat', 'Viagra', 'Tidak aman: dapat menyebabkan pingsan'),
('Nitrat', 'Aspirin', 'Aman dengan pengawasan'),
('Vitamin B Complex', 'Paracetamol', 'Aman dikonsumsi bersamaan'),
('Vitamin B Complex', 'Metformin', 'Aman dikonsumsi bersamaan'),
('Kafein', 'Diazepam', 'Tidak aman: mengurangi efek sedatif'),
('Kafein', 'Salbutamol', 'Tidak aman: meningkatkan jantung berdebar'),
('Kafein', 'Paracetamol', 'Aman dikonsumsi bersamaan'),
('Alkohol', 'Metformin', 'Tidak aman: risiko asidosis laktat'),
('Alkohol', 'Diazepam', 'Tidak aman: depresi napas'),
('Alkohol', 'Simvastatin', 'Tidak aman: kerusakan hati'),
('Alkohol', 'Paracetamol', 'Tidak aman: hepatotoksik'),
('Susu', 'Ciprofloxacin', 'Tidak aman: menghambat penyerapan'),
('Susu', 'Doxycycline', 'Tidak aman: efektivitas antibiotik turun'),
('Susu', 'Paracetamol', 'Aman dikonsumsi bersamaan'),
('Pil KB', 'Rifampicin', 'Tidak aman: efektivitas kontrasepsi menurun'),
('Pil KB', 'Amoxicillin', 'Aman dengan pengawasan'),
('Pil KB', 'Paracetamol', 'Aman dikonsumsi bersamaan'),
('NSAID', 'Warfarin', 'Tidak aman: meningkatkan perdarahan'),
('NSAID', 'Paracetamol', 'Aman dengan batas dosis'),
('NSAID', 'Prednisone', 'Tidak aman: risiko tukak lambung'),
('Insulin', 'Alkohol', 'Tidak aman: hipoglikemia berat'),
('Metformin', 'Vitamin B12', 'Aman dikonsumsi bersamaan'),
('Amlodipine', 'Paracetamol', 'Aman dikonsumsi bersamaan');